version: "3.9"
services:
  app:
    build: src
    read_only: true
    networks:
      - app_network
    ports:
      - "8080:8080"
    environment:
      DEBUG: True

networks: 
  app_network:
    name: app_network
